# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
