.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Communication/CommunicationFrame.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Communication/CommunicationFrame.c
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'CommunicationFrame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAppendPayLoad\fP (PayLoad *payload, const char *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void AppendPayLoad (PayLoad * payload, const char * data)"

.PP
Definition at line 13 of file CommunicationFrame\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
