.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Communication Directory Reference" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Communication Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommunication\&.c\fP"
.br
.ti -1c
.RI "file \fBCommunicationFrame\&.c\fP"
.br
.ti -1c
.RI "file \fBprotocol\&.c\fP"
.br
.ti -1c
.RI "file \fBSerialization\&.c\fP"
.br
.ti -1c
.RI "file \fBuart_host\&.c\fP"
.br
.in -1c
