.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Accelerometer Directory Reference" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Accelerometer Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccelerometer\&.c\fP"
.br
.ti -1c
.RI "file \fBi2c\&.c\fP"
.br
.ti -1c
.RI "file \fBMMA8451\&.c\fP"
.br
.in -1c
