.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources Directory Reference" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAccelerometer\fP"
.br
.ti -1c
.RI "directory \fBApp\fP"
.br
.ti -1c
.RI "directory \fBclock\fP"
.br
.ti -1c
.RI "directory \fBCommunication\fP"
.br
.ti -1c
.RI "directory \fBGPS\fP"
.br
.ti -1c
.RI "directory \fBIHM\fP"
.br
.ti -1c
.RI "directory \fBTank\fP"
.br
.ti -1c
.RI "directory \fBUtils\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEvents\&.c\fP"
.br
.RI "This is user's event module\&. Put your event handler code here\&. "
.ti -1c
.RI "file \fBEvents\&.h\fP"
.br
.RI "This is user's event module\&. Put your event handler code here\&. "
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "
.PP
.nf
    Main module.
    This module contains user's application code.

.fi
.PP
 Ferramentas de debug https://www.nxp.com/docs/en/quick-reference-guide/MCUXpresso_IDE_FreeRTOS_Debug_Guide.pdf https://percepio.com/docs/FreeRTOS/manual/Recorder.html#Trace_Recorder_Library_Snapshot_Mode https://mcuoneclipse.com/2017/03/18/better-freertos-debugging-in-eclipse/ https://mcuoneclipse.com/2016/04/09/freertos-thread-debugging-with-eclipse-and-openocd/ "
.in -1c
