.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/IHM/lcd.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/IHM/lcd.c
.SH SYNOPSIS
.br
.PP
\fC#include 'LCDout\&.h'\fP
.br
\fC#include 'lcd\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLCDInit\fP ()"
.br
.ti -1c
.RI "void \fBLCDWrite\fP (char ch)"
.br
.ti -1c
.RI "void \fBLCDWriteLn\fP (void)"
.br
.ti -1c
.RI "void \fBLCDWriteLineStr\fP (byte line, char *str)"
.br
.ti -1c
.RI "void \fBLCDWriteString\fP (char *str)"
.br
.ti -1c
.RI "void \fBLCDShiftLeft\fP (void)"
.br
.ti -1c
.RI "void \fBLCDShiftRight\fP (void)"
.br
.ti -1c
.RI "void \fBLCDGotoXY\fP (byte line, byte column)"
.br
.ti -1c
.RI "void \fBLCDSetEntryMode\fP (bool increment, bool shiftLeft)"
.br
.ti -1c
.RI "void \fBLCDCursorShiftRight\fP (void)"
.br
.ti -1c
.RI "void \fBLCDCursorShiftLeft\fP (void)"
.br
.ti -1c
.RI "void \fBLCDHome\fP (void)"
.br
.ti -1c
.RI "void \fBLCDLine\fP (byte line)"
.br
.ti -1c
.RI "void \fBLCDClear\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LCDClear (void)\fC [inline]\fP"

.PP
Definition at line 91 of file lcd\&.c\&.
.SS "void LCDCursorShiftLeft (void)\fC [inline]\fP"

.PP
Definition at line 73 of file lcd\&.c\&.
.SS "void LCDCursorShiftRight (void)\fC [inline]\fP"

.PP
Definition at line 67 of file lcd\&.c\&.
.SS "void LCDGotoXY (byte line, byte column)\fC [inline]\fP"

.PP
Definition at line 55 of file lcd\&.c\&.
.SS "void LCDHome (void)\fC [inline]\fP"

.PP
Definition at line 79 of file lcd\&.c\&.
.SS "void LCDInit ()\fC [inline]\fP"

.PP
Definition at line 11 of file lcd\&.c\&.
.SS "void LCDLine (byte line)\fC [inline]\fP"

.PP
Definition at line 85 of file lcd\&.c\&.
.SS "void LCDSetEntryMode (bool increment, bool shiftLeft)\fC [inline]\fP"

.PP
Definition at line 61 of file lcd\&.c\&.
.SS "void LCDShiftLeft (void)\fC [inline]\fP"

.PP
Definition at line 43 of file lcd\&.c\&.
.SS "void LCDShiftRight (void)\fC [inline]\fP"

.PP
Definition at line 49 of file lcd\&.c\&.
.SS "void LCDWrite (char ch)\fC [inline]\fP"

.PP
Definition at line 19 of file lcd\&.c\&.
.SS "void LCDWriteLineStr (byte line, char * str)\fC [inline]\fP"

.PP
Definition at line 31 of file lcd\&.c\&.
.SS "void LCDWriteLn (void)\fC [inline]\fP"

.PP
Definition at line 25 of file lcd\&.c\&.
.SS "void LCDWriteString (char * str)\fC [inline]\fP"

.PP
Definition at line 37 of file lcd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
