.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Tank/level_sensor.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Tank/level_sensor.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'level_sensor\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBBOARD_ConfigTriggerSource\fP (void)"
.br
.ti -1c
.RI "bool \fBreadValues\fP (uint32_t *val)"
.br
.ti -1c
.RI "bool \fBstart_measure\fP (void)"
.br
.ti -1c
.RI "void \fBlevel_sensor_init\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void BOARD_ConfigTriggerSource (void)"

.SS "void level_sensor_init (void)"

.PP
Definition at line 95 of file level_sensor\&.c\&.
.SS "bool readValues (uint32_t * val)"
Leitura do tanque 
.PP
Definition at line 60 of file level_sensor\&.c\&.
.SS "bool start_measure (void)"

.PP
Definition at line 85 of file level_sensor\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
