.TH "main_module" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main_module
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsys_init\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 112 of file main\&.c\&.
.SS "void sys_init (void)"

.IP "\(bu" 2
Including needed modules to compile this module/procedure */ 
.PP

.PP
Definition at line 91 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
