.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/main.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/main.c \- 
.PP
.nf
    Main module.
    This module contains user's application code.

.fi
.PP
 Ferramentas de debug https://www.nxp.com/docs/en/quick-reference-guide/MCUXpresso_IDE_FreeRTOS_Debug_Guide.pdf https://percepio.com/docs/FreeRTOS/manual/Recorder.html#Trace_Recorder_Library_Snapshot_Mode https://mcuoneclipse.com/2017/03/18/better-freertos-debugging-in-eclipse/ https://mcuoneclipse.com/2016/04/09/freertos-thread-debugging-with-eclipse-and-openocd/  

.SH SYNOPSIS
.br
.PP
\fC#include 'Cpu\&.h'\fP
.br
\fC#include 'Events\&.h'\fP
.br
\fC#include 'FRTOS1\&.h'\fP
.br
\fC#include 'AS1\&.h'\fP
.br
\fC#include 'ASerialLdd1\&.h'\fP
.br
\fC#include 'LED_G\&.h'\fP
.br
\fC#include 'LEDpin2\&.h'\fP
.br
\fC#include 'BitIoLdd2\&.h'\fP
.br
\fC#include 'LED_R\&.h'\fP
.br
\fC#include 'LEDpin1\&.h'\fP
.br
\fC#include 'BitIoLdd1\&.h'\fP
.br
\fC#include 'LED_B\&.h'\fP
.br
\fC#include 'LEDpin3\&.h'\fP
.br
\fC#include 'BitIoLdd3\&.h'\fP
.br
\fC#include 'LCDout\&.h'\fP
.br
\fC#include 'EN1\&.h'\fP
.br
\fC#include 'BitIoLdd6\&.h'\fP
.br
\fC#include 'RS1\&.h'\fP
.br
\fC#include 'BitIoLdd7\&.h'\fP
.br
\fC#include 'DB41\&.h'\fP
.br
\fC#include 'BitIoLdd12\&.h'\fP
.br
\fC#include 'DB51\&.h'\fP
.br
\fC#include 'BitIoLdd13\&.h'\fP
.br
\fC#include 'DB61\&.h'\fP
.br
\fC#include 'BitIoLdd14\&.h'\fP
.br
\fC#include 'DB71\&.h'\fP
.br
\fC#include 'BitIoLdd15\&.h'\fP
.br
\fC#include 'XF1\&.h'\fP
.br
\fC#include 'AS2\&.h'\fP
.br
\fC#include 'ASerialLdd2\&.h'\fP
.br
\fC#include 'WAIT1\&.h'\fP
.br
\fC#include 'MCUC1\&.h'\fP
.br
\fC#include 'UTIL1\&.h'\fP
.br
\fC#include 'WAIT2\&.h'\fP
.br
\fC#include 'WAIT3\&.h'\fP
.br
\fC#include 'WAIT4\&.h'\fP
.br
\fC#include 'I2C2\&.h'\fP
.br
\fC#include 'AD1\&.h'\fP
.br
\fC#include 'AdcLdd1\&.h'\fP
.br
\fC#include 'RTC1\&.h'\fP
.br
\fC#include 'EInt1\&.h'\fP
.br
\fC#include 'ExtIntLdd1\&.h'\fP
.br
\fC#include 'PE_Types\&.h'\fP
.br
\fC#include 'PE_Error\&.h'\fP
.br
\fC#include 'PE_Const\&.h'\fP
.br
\fC#include 'IO_Map\&.h'\fP
.br
\fC#include 'Telemetria\&.h'\fP
.br
\fC#include 'application\&.h'\fP
.br
\fC#include 'ihm\&.h'\fP
.br
\fC#include 'clock\&.h'\fP
.br
\fC#include 'communication\&.h'\fP
.br
\fC#include 'accelerometer\&.h'\fP
.br
\fC#include 'gps\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsys_init\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
    Main module.
    This module contains user's application code.

.fi
.PP
 Ferramentas de debug https://www.nxp.com/docs/en/quick-reference-guide/MCUXpresso_IDE_FreeRTOS_Debug_Guide.pdf https://percepio.com/docs/FreeRTOS/manual/Recorder.html#Trace_Recorder_Library_Snapshot_Mode https://mcuoneclipse.com/2017/03/18/better-freertos-debugging-in-eclipse/ https://mcuoneclipse.com/2016/04/09/freertos-thread-debugging-with-eclipse-and-openocd/ 


.PP
\fBVersion:\fP
.RS 4
01\&.01 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
