.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Accelerometer/MMA8451.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Accelerometer/MMA8451.c
.SH SYNOPSIS
.br
.PP
\fC#include 'MMA8451\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBMMA845x_getXYZ\fP (Accelerometer *acc)"
.br
.ti -1c
.RI "bool \fBMMA845x_init\fP (void)"
.br
.ti -1c
.RI "void \fBMMA845x_deInit\fP (void)"
.br
.ti -1c
.RI "void \fBMMA845x_Standby\fP (void)"
.br
.ti -1c
.RI "void \fBMMA845x_Active\fP (void)"
.br
.ti -1c
.RI "bool \fBMMA845x_Config\fP (void)"
.br
.ti -1c
.RI "bool \fBMMA845x_getRange\fP (mma8451_range_t *range)"
.br
.ti -1c
.RI "bool \fBMMA845x_Reset\fP (void)"
.br
.ti -1c
.RI "uint8_t \fBMMA845x_getOrientation\fP (void)"
.br
.ti -1c
.RI "void \fBMMA845x_setDataRate\fP (mma8451_dataRate_t dataRate)"
.br
.ti -1c
.RI "void \fBMMA845x_setNoise\fP (bool flag)"
.br
.ti -1c
.RI "void \fBMMA845x_setRange\fP (mma8451_range_t range)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void MMA845x_Active (void)"

.PP
Definition at line 93 of file MMA8451\&.c\&.
.SS "bool MMA845x_Config (void)"

.PP
Definition at line 102 of file MMA8451\&.c\&.
.SS "void MMA845x_deInit (void)\fC [inline]\fP"

.PP
Definition at line 80 of file MMA8451\&.c\&.
.SS "uint8_t MMA845x_getOrientation (void)"

.PP
Definition at line 177 of file MMA8451\&.c\&.
.SS "bool MMA845x_getRange (mma8451_range_t * range)"

.PP
Definition at line 144 of file MMA8451\&.c\&.
.SS "bool MMA845x_getXYZ (Accelerometer * acc)"
Realiza a leitura de todos os eixos 
.PP
Definition at line 14 of file MMA8451\&.c\&.
.SS "bool MMA845x_init (void)"

.PP
Definition at line 53 of file MMA8451\&.c\&.
.SS "bool MMA845x_Reset (void)"

.PP
Definition at line 159 of file MMA8451\&.c\&.
.SS "void MMA845x_setDataRate (mma8451_dataRate_t dataRate)"

.PP
Definition at line 187 of file MMA8451\&.c\&.
.SS "void MMA845x_setNoise (bool flag)"

.PP
Definition at line 205 of file MMA8451\&.c\&.
.SS "void MMA845x_setRange (mma8451_range_t range)"

.PP
Definition at line 227 of file MMA8451\&.c\&.
.SS "void MMA845x_Standby (void)"

.PP
Definition at line 84 of file MMA8451\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
