.TH "F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Utils/RingBuffer.c" 3 "Sun Jan 21 2018" "GoodsTracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/workspace/gtracker/platform/GoodsTrackerControl/Sources/Utils/RingBuffer.c
.SH SYNOPSIS
.br
.PP
\fC#include 'portmacro\&.h'\fP
.br
\fC#include 'RingBuffer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBputData\fP (RingBuffer *buffer, char ch)"
.br
.ti -1c
.RI "bool \fBgetData\fP (RingBuffer *buffer, char *ch)"
.br
.ti -1c
.RI "short \fBgetCount\fP (RingBuffer *buffer)"
.br
.ti -1c
.RI "void \fBputString\fP (RingBuffer *buffer, char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "short getCount (RingBuffer * buffer)\fC [inline]\fP"

.PP
Definition at line 71 of file RingBuffer\&.c\&.
.SS "bool getData (RingBuffer * buffer, char * ch)"

.PP
Definition at line 43 of file RingBuffer\&.c\&.
.SS "bool putData (RingBuffer * buffer, char ch)"

.PP
Definition at line 11 of file RingBuffer\&.c\&.
.SS "void putString (RingBuffer * buffer, char * str)"

.PP
Definition at line 77 of file RingBuffer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GoodsTracker from the source code\&.
