/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : GT_TSK.c
**     CDE edition : Community
**     Project     : GoodsTrackerControl
**     Processor   : MKL25Z128VLK4
**     Component   : FreeRTOS_Tasks
**     Version     : Component 01.008, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-06-20, 18:48, # CodeGen: 13
**     Abstract    :
**
**     Settings    :
**          Component Name                                 : GT_TSK
**          FreeRTOS                                       : GT_FRTOS
**          Number of tasks                                : 4
**            FreeRTOS task                                : main_taskTask
**              Task name                                  : main_task
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 0
**            FreeRTOS task                                : IHM_taskTask
**              Task name                                  : IHM_task
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 0
**            FreeRTOS task                                : communication_taskTask
**              Task name                                  : communication_task
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 0
**            FreeRTOS task                                : data_taskTask
**              Task name                                  : data_task
**              Stack size (plus configMINIMAL_STACK_SIZE) : 0
**              Initial Priority                           : 0
**     Contents    :
**         CreateTasks - void GT_TSK_CreateTasks(void);
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Omar Isaí Pinales Ayala, 2014, all rights reserved.
**     http      : http://www.mcuoneclipse.com
**     This an open source software driver for Processor Expert.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file GT_TSK.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup GT_TSK_module GT_TSK module documentation
**  @{
*/         

/* MODULE GT_TSK. */

#include "GT_TSK.h"
#include "frtos_tasks.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  GT_TSK_CreateTasks (component FreeRTOS_Tasks)
**     Description :
**         Creates the tasks.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GT_TSK_CreateTasks(void)
{
  CreateTasks();
}


#ifdef __cplusplus
}  /* extern "C" */
#endif
/* END GT_TSK. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
